import os
import logging
import subprocess
import json
import config
from core import register_command
from config import get_qmd_executable, QMD_BIN, QMD_WRAPPER

_log = logging.getLogger(__name__)

# router.py와 동일한 패턴을 재사용 (import 순환 방지를 위해 여기서 정의)
# 백업/이전 버전 디렉토리 — QMD 인덱스에서 제외할 패턴
# 주의: -v\d+[-./] 같은 범용 패턴은 오탐 위험이 있으므로
#        vega-/tools-backup 리터럴 매칭 + backup/bak/old 키워드만 사용
import re
_EXCLUDE_DIR_RE = re.compile(
    r'(?:^|[-/])(?:backup|bak|old)(?:[-/]|$)|'     # backup/bak/old 디렉토리
    r'(?:^|/)vega-v\d+[-/.]|'                        # vega-v1.xx 버전 디렉토리
    r'(?:^|/)tools-backup',                           # tools-backup 디렉토리
    re.IGNORECASE,
)


def _write_qmdignore(md_dir):
    """MD_DIR 내 백업/이전 버전 디렉토리를 스캔하여 .qmdignore 생성.

    Returns (ignore_path, excluded_dirs) 튜플.
    Raises ValueError on write failure.
    """
    excluded = []
    try:
        for entry in os.listdir(md_dir):
            full = os.path.join(md_dir, entry)
            if os.path.isdir(full) and _EXCLUDE_DIR_RE.search(entry):
                excluded.append(entry)
    except OSError as e:
        _log.warning("md_dir 스캔 실패: %s — %s", md_dir, e)

    ignore_path = os.path.join(md_dir, '.qmdignore')
    lines = [
        '# Auto-generated by vega qmd-index clean (v1.34)',
        '# 백업/이전 버전 디렉토리 제외',
        '',
    ]
    for d in sorted(set(excluded)):
        lines.append(f'{d}/')
    # 비프로젝트 파일
    lines.extend([
        '',
        '# 비프로젝트 파일',
        'INDEX.md',
        'README.md',
        'CLAUDE.md',
        'CHANGELOG.md',
        'TODO.md',
        'LICENSE.md',
    ])
    try:
        with open(ignore_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines) + '\n')
    except OSError as e:
        raise ValueError(f".qmdignore 쓰기 실패: {e}") from e

    return ignore_path, excluded


@register_command('qmd-status', needs_db=False, read_only=True, category='system')
def _exec_qmd_status(params=None):
    """QMD 2.0 시스템 상태 조회"""
    exe = get_qmd_executable()
    result = {
        'qmd_available': bool(exe),
        'qmd_binary': QMD_BIN or '(미설치)',
        'qmd_wrapper': QMD_WRAPPER or '(미설정)',
        'executable': exe or '(없음)',
        'md_dir': config.MD_DIR,
    }

    if not exe:
        result['summary'] = 'QMD 미설치. npm install -g @tobilu/qmd 로 설치하세요.'
        result['install_guide'] = {
            'install': 'npm install -g @tobilu/qmd',
            'verify': 'qmd --version',
            'setup': [
                'qmd collection add <projects_dir> --name projects',
                'qmd context add qmd://projects "태양광/풍력/ESS 프로젝트 데이터"',
                'qmd embed',
            ],
            'claude_code': 'qmd skill install',
        }
        return result

    # QMD 상태 조회 (버전 + 컬렉션 + 인덱스)
    try:
        st_result = subprocess.run(
            [QMD_BIN or exe, 'status'],
            capture_output=True, text=True, timeout=15
        )
        if st_result.returncode == 0:
            result['status_output'] = st_result.stdout.strip()
    except Exception as e:
        result['status_error'] = str(e)

    # 버전 확인
    try:
        ver_result = subprocess.run(
            [QMD_BIN or exe, '--version'],
            capture_output=True, text=True, timeout=10
        )
        result['version'] = ver_result.stdout.strip() or 'unknown'
    except Exception:
        result['version'] = 'unknown'

    # 컬렉션 목록
    try:
        col_result = subprocess.run(
            [QMD_BIN or exe, 'collection', 'list'],
            capture_output=True, text=True, timeout=10
        )
        if col_result.returncode == 0:
            result['collections'] = col_result.stdout.strip()
    except Exception:
        pass

    result['summary'] = f"QMD {result.get('version', '?')}, {'연결됨' if exe else '미연결'}"
    return result


@register_command('qmd-index', needs_db=False, read_only=False, category='system')
def _exec_qmd_index(params=None):
    """QMD 2.0 인덱스 관리 — 프로젝트 .md 파일을 QMD에 등록/갱신"""
    sub_args = (params or {}).get('sub_args', [])
    action = sub_args[0] if sub_args else 'update'

    qmd_bin = QMD_BIN or get_qmd_executable()
    if not qmd_bin:
        return {
            'error': 'QMD 미설치. npm install -g @tobilu/qmd 로 설치하세요.',
            'summary': 'QMD 미설치'
        }

    md_dir = config.MD_DIR
    if not os.path.isdir(md_dir):
        return {
            'error': f'프로젝트 디렉토리 없음: {md_dir}',
            'summary': 'MD_DIR 없음'
        }

    result = {'action': action, 'md_dir': md_dir}

    if action == 'setup':
        # 전체 초기 설정: .qmdignore 생성 + 컬렉션 등록 + 컨텍스트 + 임베딩
        steps = []
        try:
            # 0. .qmdignore 생성 (백업 디렉토리 제외)
            ignore_path, excluded = _write_qmdignore(md_dir)
            steps.append({'step': 'qmdignore', 'success': True,
                         'output': f'.qmdignore 생성 ({len(excluded)}개 디렉토리 제외)'})

            # 1. 컬렉션 등록
            r = subprocess.run(
                [qmd_bin, 'collection', 'add', md_dir, '--name', 'projects'],
                capture_output=True, text=True, timeout=30
            )
            steps.append({'step': 'collection_add', 'success': r.returncode == 0,
                         'output': (r.stdout or r.stderr or '').strip()})

            # 2. 컨텍스트 추가
            r = subprocess.run(
                [qmd_bin, 'context', 'add', 'qmd://projects',
                 '태양광/풍력/ESS 프로젝트 데이터 — 고객사, 담당자, 상태, 커뮤니케이션 이력'],
                capture_output=True, text=True, timeout=10
            )
            steps.append({'step': 'context_add', 'success': r.returncode == 0,
                         'output': (r.stdout or r.stderr or '').strip()})

            # 3. 인덱스 업데이트
            r = subprocess.run(
                [qmd_bin, 'update'],
                capture_output=True, text=True, timeout=60
            )
            steps.append({'step': 'update', 'success': r.returncode == 0,
                         'output': (r.stdout or r.stderr or '').strip()})

            result['steps'] = steps
            all_ok = all(s['success'] for s in steps)
            result['success'] = all_ok
            result['summary'] = f"QMD 초기 설정 {'완료' if all_ok else '부분 실패'}"

            if all_ok:
                result['next'] = '벡터 임베딩 생성: qmd-index embed (선택, 의미 검색용)'
        except Exception as e:
            result['error'] = str(e)
            result['summary'] = f'초기 설정 실패: {e}'

    elif action == 'add':
        collection_name = sub_args[1] if len(sub_args) > 1 else 'projects'
        try:
            r = subprocess.run(
                [qmd_bin, 'collection', 'add', md_dir, '--name', collection_name],
                capture_output=True, text=True, timeout=30
            )
            result['stdout'] = r.stdout.strip()
            result['stderr'] = r.stderr.strip()
            result['success'] = r.returncode == 0
            result['summary'] = f"컬렉션 '{collection_name}' {'등록 완료' if result['success'] else '등록 실패'}"
        except Exception as e:
            result['error'] = str(e)
            result['summary'] = f'컬렉션 등록 실패: {e}'

    elif action == 'update':
        try:
            r = subprocess.run(
                [qmd_bin, 'update'],
                capture_output=True, text=True, timeout=120
            )
            result['stdout'] = r.stdout.strip()
            result['success'] = r.returncode == 0
            result['summary'] = f"인덱스 {'업데이트 완료' if result['success'] else '업데이트 실패'}"
        except subprocess.TimeoutExpired:
            result['error'] = '인덱스 업데이트 타임아웃 (2분)'
            result['summary'] = '타임아웃'
        except Exception as e:
            result['error'] = str(e)
            result['summary'] = f'업데이트 실패: {e}'

    elif action == 'embed':
        try:
            r = subprocess.run(
                [qmd_bin, 'embed'],
                capture_output=True, text=True, timeout=600
            )
            result['stdout'] = r.stdout.strip()
            result['stderr'] = r.stderr.strip()
            result['success'] = r.returncode == 0
            result['summary'] = f"임베딩 {'완료' if result['success'] else '실패'}"
        except subprocess.TimeoutExpired:
            result['error'] = '임베딩 타임아웃 (10분). 터미널에서 직접: qmd embed'
            result['summary'] = '임베딩 타임아웃'
        except Exception as e:
            result['error'] = str(e)
            result['summary'] = f'임베딩 실패: {e}'

    elif action == 'skill-install':
        # Claude Code 플러그인 설치
        try:
            r = subprocess.run(
                [qmd_bin, 'skill', 'install'],
                capture_output=True, text=True, timeout=30
            )
            result['stdout'] = r.stdout.strip()
            result['success'] = r.returncode == 0
            result['summary'] = f"Claude Code 스킬 {'설치 완료' if result['success'] else '설치 실패'}"
        except Exception as e:
            result['error'] = str(e)
            result['summary'] = f'스킬 설치 실패: {e}'

    elif action == 'clean':
        # .qmdignore 생성 + 인덱스 재빌드
        try:
            ignore_path, excluded = _write_qmdignore(md_dir)
            result['qmdignore'] = ignore_path
            result['excluded_dirs'] = excluded

            # 인덱스 재빌드
            r = subprocess.run(
                [qmd_bin, 'update'],
                capture_output=True, text=True, timeout=120
            )
            result['stdout'] = r.stdout.strip()
            result['success'] = r.returncode == 0
            result['summary'] = (
                f".qmdignore 생성 ({len(excluded)}개 디렉토리 제외), "
                f"인덱스 {'재빌드 완료' if result['success'] else '재빌드 실패'}"
            )
        except subprocess.TimeoutExpired:
            result['error'] = '인덱스 재빌드 타임아웃 (2분)'
            result['summary'] = '타임아웃'
        except Exception as e:
            result['error'] = str(e)
            result['summary'] = f'클린 실패: {e}'

    elif action == 'embed-local':
        # v1.4: 로컬 모델로 전체 chunks 임베딩 생성
        try:
            from models import embed_all_chunks
            stats = embed_all_chunks(db_path=config.DB_PATH)
            result['stats'] = stats
            result['success'] = stats['errors'] == 0
            result['summary'] = (
                f"로컬 임베딩 완료: {stats['embedded']}건 생성, "
                f"{stats['errors']}건 오류 (전체 {stats['total']}건)"
            )
        except ImportError:
            result['error'] = 'llama-cpp-python 또는 numpy 미설치. pip install llama-cpp-python numpy'
            result['summary'] = '의존성 미설치'
        except Exception as e:
            result['error'] = str(e)
            result['summary'] = f'로컬 임베딩 실패: {e}'

    elif action == 'model-status':
        # v1.4: 로컬 모델 상태 조회
        try:
            from models import ModelManager
            mgr = ModelManager()
            result['models'] = mgr.status()
            result['inference_backend'] = config.INFERENCE_BACKEND
            result['success'] = True
            # 요약
            status_parts = []
            for role, info in result['models'].items():
                if isinstance(info, dict) and 'file_exists' in info:
                    icon = '✅' if info['file_exists'] else '❌'
                    loaded = ' (로드됨)' if info.get('loaded') else ''
                    size = f" {info['file_size_mb']}MB" if info.get('file_size_mb') else ''
                    status_parts.append(f"{icon} {role}{size}{loaded}")
            result['summary'] = f"백엔드: {config.INFERENCE_BACKEND} | " + ', '.join(status_parts)
        except ImportError:
            result['error'] = 'llama-cpp-python 미설치'
            result['summary'] = '의존성 미설치'
        except Exception as e:
            result['error'] = str(e)
            result['summary'] = f'모델 상태 조회 실패: {e}'

    elif action == 'status':
        from core import execute
        return execute('qmd-status', {}).get('data', {})

    else:
        result['error'] = f"알 수 없는 액션: {action}"
        result['usage'] = 'qmd-index [setup|update|add|embed|embed-local|clean|skill-install|model-status|status]'
        result['summary'] = f'알 수 없는 액션: {action}'

    return result
